import type { DraftSentence, DraftTable } from "./draft.ts"

/**
 * The READING projection — a self-contained HTML artifact generated BY CODE
 * from the verification record (zero model tokens). This is the surface for
 * reading, sharing, and printing:
 *  - real academic typography + print CSS (browser "Save as PDF" replaces
 *    the old bare print pipeline);
 *  - every citation marker links to its reference entry, and every reference
 *    deep-links into the app's copy of the PDF at its first cited page
 *    (/api/file?path=…#page=N — browsers open PDFs at page anchors);
 *  - a "verification" toggle overlays the verdict colors when auditing.
 */

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")

/** minimal inline markdown: **bold** / *italic* — nothing else survives upstream */
function inline(s: string): string {
  return esc(s)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/(^|[\s(])\*([^*\s][^*]*)\*(?=[\s).,;:]|$)/g, "$1<em>$2</em>")
}

export interface HtmlRef {
  num: number
  path: string
  /** registry identity ("Hooker et al., 2020 — \"Title\"") or path fallback */
  label: string
  grade: string
  /** first cited page — the deep-link target */
  page: number | null
}

export function renderDraftHtml(args: {
  title: string
  sentences: DraftSentence[]
  tables: DraftTable[]
  refs: HtmlRef[]
  citeNums: (cites: string[]) => number[]
  citeText?: (cites: string[]) => string | null
  summaryLine: string
  /** plain document — no verification toggle, no references section */
  plain?: boolean
}): string {
  const { title, sentences, tables, refs, citeNums, citeText, summaryLine, plain } = args
  const marker = (cites: string[]) => {
    const nums = citeNums(cites)
    if (nums.length === 0) return ""
    const label = citeText?.(cites) ?? `[${nums.join(", ")}]`
    // one anchor per marker, pointing at the first reference it cites
    return ` <a class="cite" href="#ref-${nums[0]}">${esc(label)}</a>`
  }
  const sentenceSpan = (s: DraftSentence) =>
    plain
      ? inline(s.text) // plain documents carry no verdict spans — bare prose
      : `<span class="s v-${s.verdict}">${inline(s.text)}${marker(s.cites)}</span>`

  const tableHtml = (t: DraftTable) => {
    const head = t.columns.map((c) => `<th>${inline(c)}</th>`).join("")
    const rows = t.rows
      .map(
        (r) =>
          `<tr>${t.columns
            .map((_, ci) => {
              const cell = r[ci]
              const cellBody = cell ? inline(cell.text) + (plain ? "" : marker(cell.cites)) : ""
              return plain ? `<td>${cellBody}</td>` : `<td class="v-${cell?.verdict ?? "uncited"}">${cellBody}</td>`
            })
            .join("")}</tr>`,
      )
      .join("")
    const cap = t.caption ? `<caption>${inline(t.caption)}</caption>` : ""
    return `<table>${cap}<thead><tr>${head}</tr></thead><tbody>${rows}</tbody></table>`
  }

  // group by section, then by block structure (paragraphs / lists / h3)
  const norm = (h: string | null) => (h ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim()
  const tablesByHeading = new Map<string, DraftTable[]>()
  for (const t of tables) {
    const k = norm(t.heading)
    tablesByHeading.set(k, [...(tablesByHeading.get(k) ?? []), t])
  }
  const sections: { heading: string | null; sentences: DraftSentence[] }[] = []
  for (const s of sentences) {
    if (s.heading || sections.length === 0) sections.push({ heading: s.heading ?? null, sentences: [] })
    sections[sections.length - 1]!.sentences.push(s)
  }
  const sectionHtml = (sec: (typeof sections)[number]) => {
    let out = sec.heading ? `<h2>${inline(sec.heading)}</h2>` : ""
    let buf: string[] = []
    let list: { ordered: boolean; items: string[] } | null = null
    const flushP = () => {
      if (buf.length) out += `<p>${buf.join(" ")}</p>`
      buf = []
    }
    const flushL = () => {
      if (list) {
        const tag = list.ordered ? "ol" : "ul"
        out += `<${tag}>${list.items.map((i) => `<li>${i}</li>`).join("")}</${tag}>`
      }
      list = null
    }
    for (const s of sec.sentences) {
      const b = s.block ?? "p"
      if (b === "h3") {
        flushP()
        flushL()
        out += `<h3>${inline(s.text)}</h3>`
      } else if (b === "li") {
        flushP()
        if (!list || list.ordered !== (s.ordered ?? false)) {
          flushL()
          list = { ordered: s.ordered ?? false, items: [] }
        }
        list.items.push(sentenceSpan(s))
      } else {
        flushL()
        if (s.newPara) flushP()
        buf.push(sentenceSpan(s))
      }
    }
    flushP()
    flushL()
    for (const t of tablesByHeading.get(norm(sec.heading)) ?? []) out += tableHtml(t)
    return out
  }

  const refsHtml = refs
    .map((r) => {
      const href = `/api/file?path=${encodeURIComponent(r.path)}${r.page ? `#page=${r.page}` : ""}`
      return `<li id="ref-${r.num}"><a href="${href}">${inline(r.label)}</a> <span class="grade">(${esc(r.grade)}${r.page ? ` · p.${r.page}` : ""})</span></li>`
    })
    .join("")

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)}</title>
<style>
  body { font-family: Charter, Georgia, "Times New Roman", serif; color: #1c1e21; max-width: 720px;
         margin: 48px auto; padding: 0 20px; line-height: 1.72; font-size: 16px; }
  h1 { font-size: 26px; line-height: 1.25; margin: 0 0 4px; }
  .meta { font-family: ui-monospace, Menlo, monospace; font-size: 11px; color: #777; margin-bottom: 28px; }
  h2 { font-size: 19px; margin: 30px 0 8px; }
  h3 { font-size: 16px; margin: 20px 0 6px; }
  p { margin: 10px 0; text-align: justify; hyphens: auto; }
  ul, ol { margin: 10px 0; padding-left: 26px; }
  a.cite { color: #245e9c; text-decoration: none; }
  a.cite:hover { text-decoration: underline; }
  table { border-collapse: collapse; margin: 16px 0; font-size: 14px; width: 100%; }
  caption { caption-side: top; font-style: italic; font-size: 13px; text-align: left; padding-bottom: 4px; }
  th, td { border: 1px solid #ccc; padding: 5px 9px; text-align: left; vertical-align: top; }
  th { background: #f6f5f2; }
  .refs { margin-top: 34px; border-top: 1px solid #ddd; padding-top: 12px; }
  .refs li { margin: 6px 0; font-size: 14.5px; }
  .refs a { color: inherit; }
  .grade { color: #999; font-size: 12px; }
${plain ? "" : `  /* verification overlay — off unless toggled */
  #v:checked ~ main .v-supported { border-bottom: 2px solid #3d9a5f55; }
  #v:checked ~ main .v-partial { border-bottom: 2px solid #d99a2b66; }
  #v:checked ~ main .v-unsupported { border-bottom: 2px solid #c9463d77; }
  #v:checked ~ main td.v-supported { background: #3d9a5f14; }
  #v:checked ~ main td.v-partial { background: #d99a2b14; }
  #v:checked ~ main td.v-unsupported { background: #c9463d14; }
  .toggle { font-family: ui-monospace, Menlo, monospace; font-size: 11px; color: #777; user-select: none; }`}
  @media print { .toggle { display: none; } body { margin: 0 auto; font-size: 11.5pt; } a.cite { color: inherit; } }
</style></head>
<body>
${plain ? "" : `<input type="checkbox" id="v" hidden>`}
<h1>${esc(title)}</h1>
${plain ? "" : `<div class="meta">${esc(summaryLine)} · <label class="toggle" for="v">☑ toggle verification overlay</label></div>`}
<main>
${sections.map(sectionHtml).join("\n")}
${plain || refs.length === 0 ? "" : `<div class="refs"><h2>References</h2><ol>${refsHtml}</ol></div>`}
</main>
</body></html>`
}
