// Build standalone executables — Bun, the app, the web UI, and the native canvas
// library in one file, so users need nothing else installed.
//
//   bun run scripts/compile.ts                  # this machine's platform
//   bun run scripts/compile.ts --all            # every supported platform
//   bun run scripts/compile.ts linux-x64 ...    # specific ones
//
// Output: apps/cli/dist-bin/abstract-<target>.tar.gz + SHA256SUMS
import { createHash } from "node:crypto"
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, relative } from "node:path"

const TARGETS: Record<string, string> = {
  // target → the canvas package carrying that platform's native library
  "darwin-arm64": "@napi-rs/canvas-darwin-arm64",
  "darwin-x64": "@napi-rs/canvas-darwin-x64",
  "linux-x64": "@napi-rs/canvas-linux-x64-gnu",
  "linux-arm64": "@napi-rs/canvas-linux-arm64-gnu",
}
// every platform package the canvas loader may ask for — all but the target's stay external
const ALL_CANVAS = [
  ...Object.values(TARGETS),
  "@napi-rs/canvas-linux-x64-musl",
  "@napi-rs/canvas-linux-arm64-musl",
  "@napi-rs/canvas-linux-arm-gnueabihf",
  "@napi-rs/canvas-linux-riscv64-gnu",
  "@napi-rs/canvas-win32-x64-msvc",
  "@napi-rs/canvas-win32-arm64-msvc",
  "@napi-rs/canvas-android-arm64",
  "@napi-rs/canvas-freebsd-x64",
  "@napi-rs/canvas-openharmony-arm64",
]

const cli = join(import.meta.dir, "..")
const root = join(cli, "../..")
const webDist = join(root, "apps/web/dist")
const outDir = join(cli, "dist-bin")
const buildDir = join(cli, ".build")

const run = (cmd: string[], cwd = cli) => {
  const r = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" })
  if (r.exitCode !== 0) throw new Error(`failed: ${cmd.join(" ")}`)
}

const args = process.argv.slice(2)
const here = `${process.platform}-${process.arch}`
const targets = args.includes("--all") ? Object.keys(TARGETS) : args.length ? args : [here]
for (const t of targets) if (!TARGETS[t]) throw new Error(`unknown target ${t} (known: ${Object.keys(TARGETS).join(", ")})`)

if (!existsSync(join(webDist, "index.html"))) throw new Error("web UI not built — run `bun run build` at the repo root first")
const version = (JSON.parse(readFileSync(join(cli, "package.json"), "utf8")) as { version: string }).version
const canvasVersion = (
  JSON.parse(readFileSync(join(cli, "package.json"), "utf8")) as { dependencies: Record<string, string> }
).dependencies["@napi-rs/canvas"]!.replace(/^[\^~]/, "")

// 1. a generated entry that embeds every web UI file, then hands over to standalone.ts
rmSync(buildDir, { recursive: true, force: true })
mkdirSync(buildDir, { recursive: true })
const walk = (d: string): string[] =>
  readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(d, e.name)) : [join(d, e.name)]))
const webFiles = walk(webDist)
const entry = [
  "// generated by scripts/compile.ts — embeds the web UI",
  ...webFiles.map((f, i) => `import f${i} from ${JSON.stringify(f)} with { type: "file" }`),
  `globalThis.__ABSTRACT_WEB_FILES__ = {`,
  ...webFiles.map((f, i) => `  ${JSON.stringify(relative(webDist, f))}: f${i},`),
  `}`,
  `await import(${JSON.stringify(join(cli, "src/standalone.ts"))})`,
].join("\n")
const entryFile = join(buildDir, "entry.ts")
writeFileSync(entryFile, entry)

mkdirSync(outDir, { recursive: true })
const sums: string[] = []

for (const target of targets) {
  const canvasPkg = TARGETS[target]!
  // 2. make sure the target's native canvas package is installed (cross-builds fetch it)
  const pkgDir = join(root, "node_modules", canvasPkg)
  if (!existsSync(join(pkgDir, "package.json"))) {
    const tmp = join(tmpdir(), `abstract-canvas-${process.pid}-${target}`)
    mkdirSync(tmp, { recursive: true })
    run(["npm", "pack", `${canvasPkg}@${canvasVersion}`, "--silent"], tmp)
    const tgz = readdirSync(tmp).find((f) => f.endsWith(".tgz"))!
    run(["tar", "-xzf", tgz], tmp)
    mkdirSync(join(pkgDir, ".."), { recursive: true })
    cpSync(join(tmp, "package"), pkgDir, { recursive: true })
    rmSync(tmp, { recursive: true, force: true })
  }

  // 3. compile
  const dir = join(outDir, `abstract-${target}`)
  rmSync(dir, { recursive: true, force: true })
  mkdirSync(dir, { recursive: true })
  const bin = join(dir, "abstract")
  const external = ALL_CANVAS.filter((p) => p !== canvasPkg).flatMap((p) => ["--external", p])
  // x64 uses Bun's "baseline" runtime: the default one needs AVX2, which older Intel
  // machines and Rosetta lack (observed: no output at all under Rosetta)
  const bunTarget = target.endsWith("-x64") ? `bun-${target}-baseline` : `bun-${target}`
  run(["bun", "build", "--compile", "--minify", `--target=${bunTarget}`, ...external, entryFile, "--outfile", bin])

  // macOS refuses unsigned arm64 executables: ad-hoc sign (possible on macOS only)
  if (target.startsWith("darwin")) {
    if (process.platform === "darwin") run(["codesign", "--force", "--sign", "-", bin])
    else console.warn(`warning: ${target} built off macOS is unsigned and may not run`)
  }
  for (const f of ["LICENSE", "README.md"]) cpSync(join(root, f), join(dir, f))

  // 4. package + checksum
  const tarName = `abstract-${target}.tar.gz`
  // no macOS metadata in the archive (Linux tar warns about it on extraction)
  const noMeta = process.platform === "darwin" ? ["--no-mac-metadata", "--no-xattrs"] : ["--no-xattrs"]
  const tarCmd = ["tar", ...noMeta, "-czf", join(outDir, tarName), "-C", dir, "abstract", "LICENSE", "README.md"]
  const t = Bun.spawnSync(tarCmd, { cwd: cli, env: { ...process.env, COPYFILE_DISABLE: "1" }, stdout: "inherit", stderr: "inherit" })
  if (t.exitCode !== 0) throw new Error(`failed: ${tarCmd.join(" ")}`)
  const sha = createHash("sha256").update(readFileSync(join(outDir, tarName))).digest("hex")
  sums.push(`${sha}  ${tarName}`)
  console.log(`✓ ${tarName}`)
}

writeFileSync(join(outDir, "SHA256SUMS"), sums.join("\n") + "\n")
rmSync(buildDir, { recursive: true, force: true })
console.log(`abstract ${version} → ${relative(root, outDir)}`)
